spring:
  application:
    name: grocery-shop-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:grocerydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

app:
  jwt:
    secret: mySecretKeyForJWTTokenGenerationAndValidationPurposes
    expiration: 900000  # 15 minutes in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds

  cors:
    allowed-origins: http://localhost:3000,https://grocery-shop.com
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  websocket:
    enabled: true
    allowed-origins: http://localhost:3000,https://grocery-shop.com

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    doc-expansion: none

logging:
  level:
    com.groceryshop: INFO
    org.springframework.security: DEBUG
    org.springframework.modulith: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/grocery-shop.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,modulith
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
